### ISSUE TITLE
Enhancement for special instructions

### ISSUE THREAD

**Issue by smichelotti** [smichelotti/fresh-fit-fuel#53]
For each menu item, provide an area for any special instructions (e.g., hold the cucumbers).

@jennamichelotti - what do you want the label to say?

**Comment by jennamichelotti** [comment]
I’m thinking 2 sections. One with the title of like “add protein” and the other with “remove” or “remove items/ingredients”. Let me show you what I was thinking in a little bit

**Comment by smichelotti** [comment]
done
